# Generated by Django 6.1 on 2026-08-21 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='color_value',
            field=models.PositiveBigIntegerField(default=4284960932),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('theory_and_lab', 'Theory and Lab')], default='theory', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_subject_code_per_user'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
    ]
